open-eid/chrome-token-signing

host-linux/GNUmakefile
This should allow to build a .deb on actual Debian as well.
=> Remove Ubuntuism

host-osx/Makefile, host-osx/chrome-token-signing.xcodeproj/project.pbxproj
=> Fix openssl paths

host-osx/Makefile
=> Fix build with store submission certs installed

README.md
=> Add note about Firefox support

Makefile
=> Use on signing sha256 timestamp

extension/manifest.json
=> Add www.overdrive.com to exclude list

host-windows/CngCapiSigner.cpp
=> Resize signature value to actual size

extension/content.js, extension/manifest.json, extension/page.js, host-osx/PINDialog.mm, host-osx/chrome-token-signing.xcodeproj/project.pbxproj, host-windows/CngCapiSigner.cpp, host-windows/CngCapiSigner.h, host-windows/DialogManager.h, host-windows/PinDialog.cpp, host-windows/Pkcs11Signer.cpp, host-windows/Pkcs11Signer.h, host-windows/RequestHandler.cpp, host-windows/Signer.cpp, host-windows/Signer.h, host-windows/chrome-token-signing.props, host-windows/host-windows.vcxproj
=> Implement info parameter

Makefile, README.md, host-windows/chrome-token-signing.wxs
=> Use VS140 runtimes

host-linux/CertificateSelection.h, host-linux/Signer.h, host-osx/CertificateSelection.mm, host-osx/PINDialog.mm, host-shared/Labels.cpp, host-shared/Labels.h, host-shared/PKCS11Path.cpp, host-shared/PKCS11Path.h, host-windows/CertificateSelector.cpp, host-windows/CertificateSelector.h, host-windows/DialogManager.cpp, host-windows/DialogManager.h, host-windows/HostExceptions.h, host-windows/NativeCertificateSelector.cpp, host-windows/NativeCertificateSelector.h, host-windows/PKCS11CertificateSelector.cpp, host-windows/PKCS11CertificateSelector.h, host-windows/PinDialog.cpp, host-windows/PinDialog.h, host-windows/RequestHandler.cpp, host-windows/Signer.cpp, host-windows/chrome-token-signing.cpp, host-windows/host-windows.vcxproj, host-windows/host-windows.vcxproj.filters
=> Latvian and Lithuanian translations and translate windows cert/pin dialogs

host-osx/CertificateSelection.mm, host-osx/chrome-token-signing.xcodeproj/project.pbxproj
=> OSX certificate details preview

host-shared/PKCS11Path.cpp
=> OSX /System folder is protected

host-osx/chrome-host.mm
=> Read more data if packet size > data available

host-linux/CertificateSelection.h, host-osx/CertificateSelection.mm, host-windows/CertificateSelector.cpp, host-windows/CertificateSelector.h, host-windows/CngCapiSigner.cpp, host-windows/NativeCertificateSelector.cpp, host-windows/PKCS11CertificateSelector.cpp, host-windows/RequestHandler.cpp, host-windows/Signer.cpp
=> Optimize, evaluate cert expiry date, key usage before key check

host-shared/PKCS11CardManager.h
=> Find correct key by ID value

host-windows/NativeSigner.cpp
=> CNG MS SmartCard Provider is strict with RSA parameters allowed only with RSA  key

host-shared/PKCS11CardManager.h
=> Skip SLOT ID if GetTokenInfo fails

host-shared/PKCS11Path.cpp
=> Use OpenSC PKCS11 on macOS

extension/manifest.json
=> Add https://ebs.instructure.com/ to exclude list

RELEASE-NOTES.md, host-windows/PKCS11CertificateSelector.cpp
=> Fix Windows PKCS11 certificate filter

host-shared/PKCS11Path.cpp
=> Update Lithuanian driver paths

.travis.yml, host-shared/PKCS11Path.cpp
=> Add more logging

host-shared/PKCS11Path.cpp
=> Use F_OK instead to test if file exists

host-shared/BinaryUtils.cpp, host-shared/BinaryUtils.h, host-shared/PKCS11Path.cpp
=> Use SCardGetStatusChange to get ATR-s and avoid to connecting with card

host-osx/CertificateSelection.mm, host-osx/CertificateSelection.xib, host-osx/PINDialog.mm, host-osx/PINDialog.xib, host-osx/PINPadDialog.xib, host-osx/chrome-token-signing.xcodeproj/project.pbxproj
=> Fix deprecated warning

host-linux/CertificateSelection.h, host-linux/Signer.h, host-linux/chrome-token-signing.pro, host-osx/CertificateSelection.mm, host-shared/PKCS11CardManager.h
=> Filter attributes with token filter

host-linux/CertificateSelection.h, host-linux/Signer.h, host-osx/CertificateSelection.mm, host-osx/PINDialog.mm, host-shared/PKCS11CardManager.h, host-windows/PKCS11CertificateSelector.cpp, host-windows/Pkcs11Signer.cpp
=> Remove instance to allow use multiple drivers per session

host-osx/chrome-token-signing.xcodeproj/project.pbxproj, host-shared/Exceptions.h, host-windows/CertificateSelector.h, host-windows/IOCommunicator.cpp, host-windows/NativeCertificateSelector.cpp, host-windows/NativeSigner.cpp, host-windows/PKCS11CertificateSelector.cpp, host-windows/Pkcs11Signer.cpp, host-windows/RequestHandler.h, host-windows/Signer.cpp, host-windows/chrome-token-signing.cpp, host-windows/host-windows.vcxproj, host-windows/host-windows.vcxproj.filters
=> Move HostException to global

host-linux/Signer.h, host-osx/PINDialog.mm, host-shared/Exceptions.h, host-shared/PKCS11CardManager.h
=> Merge PKCS11 and global exceptions

host-linux/CertificateSelection.h, host-linux/Signer.h, host-osx/CertificateSelection.mm, host-osx/PINDialog.mm, host-osx/chrome-host.mm, host-shared/BinaryUtils.cpp, host-shared/Exceptions.h, host-shared/PKCS11CardManager.h, host-windows/PKCS11CertificateSelector.cpp, host-windows/Pkcs11Signer.cpp
=> Add driver exception

host-shared/Labels.cpp, host-shared/Logger.cpp, host-shared/pkcs11.h
=> Sync files with browser-token-signing

host-shared/Exceptions.h, host-shared/PKCS11CardManager.h, host-shared/PKCS11Path.cpp, host-windows/CertificateSelector.cpp, host-windows/NativeCertificateSelector.cpp, host-windows/NativeSigner.cpp, host-windows/PKCS11CertificateSelector.cpp, host-windows/PKCS11CertificateSelector.h, host-windows/Signer.cpp
=> Unify some code

Makefile, host-shared/Labels.cpp, host-windows/chrome-token-signing.props, host-windows/host-windows.vcxproj, host-windows/host-windows.vcxproj.filters, host-windows/stdafx.cpp
=> Enable precompiled headers to speedup compile times

host-linux/GNUmakefile, host-linux/chrome-token-signing.pro
=> Add LIBPATH qmake/make variable and select default qt5

host-osx/CertificateSelection.mm, host-osx/CertificateSelection.xib, host-osx/PINDialog.mm, host-osx/chrome-host.mm, host-osx/chrome-token-signing.xcodeproj/project.pbxproj
=> OSX: add Touch Bar support

debian/chrome-token-signing.postrm
=> Workaround when folders are missing

host-shared/PKCS11Path.cpp
=> Add Belgium middleware paths

.travis.yml, RELEASE-NOTES.md, debian/control, host-linux/GNUmakefile
=> Add missing parameter

host-osx/Makefile
=> Sign profile

host-windows/NativeCertificateSelector.cpp
=> Add hardware token filter

host-linux/Signer.h, host-osx/PINDialog.mm, host-shared/PKCS11CardManager.h, host-windows/Pkcs11Signer.cpp
=> Handle PKCS11 CKR_PIN_LOCKED error code

host-windows/chrome-token-signing.wxs
=> Add MSI option to control ExtensionInstallForceList registry key

Makefile, host-windows/chrome-token-signing.wxs, host-windows/host-windows.vcxproj, make.bat
=> Build with Visual Studio 2017

debian/control, host-shared/PKCS11Path.cpp
=> Fix linux module extension

host-shared/PKCS11Path.cpp
=> Fix linux module path (#129)

host-osx/Makefile
=> Split policy to separate installer

debian/chrome-token-signing-policy.install, debian/chrome-token-signing-policy.links, debian/chrome-token-signing-policy.lintian-overrides, debian/chrome-token-signing-policy.postinst, debian/chrome-token-signing-policy.postrm, debian/chrome-token-signing.install, debian/chrome-token-signing.links, debian/chrome-token-signing.postinst, debian/chrome-token-signing.postrm, debian/control, host-osx/Makefile
=> Split policy to separate installer (#135)

debian/control, host-osx/Makefile
IB-5865
Signed-off-by: Hans Niinemäe <hans@raulwalter.com>
=> Extra conditions for debian package updates

host-linux/chrome-host.cpp
Signed-off-by: Marin Ivanov <dev@metala.org>
=> Exit with failure when stdin is an empty file

Makefile
=> Build with Visual Studio 2015

host-windows/chrome-token-signing.wxs
IB-6035
Signed-off-by: Hans Niinemäe <hans@raulwalter.com>
=> Install chrome policy only when chrome extension is also selected

host-shared/Labels.cpp
This pull request offers Turkish language support for the chrome plugin screens.
Language labels have been added for this purpose.
=> Turkish Language Support

host-osx/CertificateSelection.xib, host-osx/PINDialog.xib, host-osx/PINPadDialog.xib
=> Fix macOS Dark Mode UI and increase version

.travis.yml, Makefile, README.md
=> Visual Studio 2019

debian/control, debian/token-signing-firefox.postinst, debian/token-signing-firefox.postrm
=> Create policies.json on ubuntu

README.md, host-windows/chrome-token-signing.wxs, host-windows/ee.ria.esteid.json
=> Edge Chromium support

host-osx/CertificateSelection.mm, host-osx/PINDialog.mm, host-osx/PINDialog.xib
=> Add Number formatter

Makefile, host-osx/chrome-token-signing.xcodeproj/project.pbxproj, host-windows/host-windows.vcxproj, host-windows/host-windows.vcxproj.filters
=> Additional signing flags and enable Guard

host-shared/PKCS11Path.cpp
=> Workaround Lithuanian middlware path issue

host-shared/PKCS11CardManager.h, host-shared/PKCS11Path.cpp
=> Fix coverity errors

host-osx/chrome-token-signing.xcodeproj/project.pbxproj, host-shared/PKCS11CardManager.h
=> Workaround Fin middleware issues

host-shared/PKCS11CardManager.h, host-windows/NativeCertificateSelector.cpp, host-windows/PinDialog.cpp, host-windows/PinDialog.h, host-windows/Pkcs11Signer.cpp, host-windows/chrome-token-signing.cpp, host-windows/host-windows.vcxproj
=> Increase windows warning level to W4 and check PIN min/max length

.github/workflows/build.yml, host-osx/CertificateSelection.mm, host-osx/PINDialog.mm, host-osx/chrome-token-signing.xcodeproj/project.pbxproj, host-shared/PKCS11CardManager.h, host-shared/PKCS11Path.cpp, host-shared/PKCS11Path.h
=> Sandbox breaks IDPrimePKCS11 module loading

host-test/host-sample.py, host-test/longrunning-test.py, host-test/pipe-test.py, host-test/stateless-test.py, host-test/testconf.py
=> Fix linux tests and reformat files

SafariAppExtension/TokenSigningApp.xcodeproj/project.pbxproj, debian/control
=> Fix SafariAppExtensions version number

extension/manifest.json
=> Update extension version number
